imdaxsz/orday-front-end

src/App.tsx, src/main.tsx
브라우저 라우팅을 위한 기본 설정
App.tsx
Main.tsx
feature #4
없음.
=> feat: 라우터 기본 설정 #4

src/App.tsx, src/main.tsx, src/styles/color.scss, src/styles/font.scss, src/styles/reset.scss, src/styles/style.scss, src/styles/theme.ts
global style 정의
- reset
- font
- color
- typo (추후 추가 예정)
theme.ts는 styled components에 사용됩니다.
이런 식으로 theme에 있는 속성을 사용하실 수 있습니다.
#2
reset 참고자료
https://meyerweb.com/eric/tools/css/reset/
=> feat: global style

src/components/Button/index.tsx, src/components/Button/style.ts, src/styles/styled.d.ts, src/styles/theme.ts
Button 컴포넌트 구현
(outline neutral 버튼은 페이지 내에 사용되지 않지만 임시로 만들었습니다.)
최대한 공통된 스타일만 Button 컴포넌트에 담았습니다.
각 사이즈별 height는 정해져 있습니다. width는 작업 시 상황에 맞게 사이즈 설정하시면 됩니다.
<br/>
다음과 같이 짧은 스타일은 style 속성으로 스타일 추가할 수 있고
```
<Button variant="outline" style={{ width: "200px" }} color="neutral">
Outline with style
</Button>
```
<br/>
추가할 스타일이 긴 경우 사진에 나온 것처럼 StyledButton과 같이 Button을 base로 한 새로운 styled 컴포넌트를 만들어서 스타일 적용해 주시면 됩니다.
<br/><br/>
+) 아래와 같이 아이콘만 들어간 버튼의 경우 padding overriding이 필요합니다.
<br/>
- Button 컴포넌트 구현
- 타입스크립트에서 theme 사용을 위해 styled.d.ts에서 DefaultTheme 타입 지정
- theme color 수정
#2 #10
버튼 및 global style은 추후 수정이 있을 수 있습니다.
코드 관련 피드백 있으시면 리뷰 부탁드립니다!
<br/>
=> feat: Button 컴포넌트

src/routes/Login/LoginForm.tsx
- 구글 로그인 버튼 추가
#29
로그인 유효성 검사는 기능 구현 시 추가하겠습니다.
=> feat: 로그인 페이지 구글 로그인 버튼 추가

src/api/ReviewApi.ts, src/components/Header/index.tsx, src/components/Header/style.ts, src/hooks/useReivewList.ts, src/hooks/useWriteReview.ts, src/routes/Review/List.tsx, src/routes/Review/Write.tsx, src/styles/GlobalStyle.tsx, src/types/global.d.ts
회원 리뷰 목록 조회, 작성, 수정 구현
- production api로 전부 테스트 완료되었습니다.
- 리뷰 작성/수정 중 이미지 업로드 시, 작성/수정 요청 시 로딩 상태일 때 Loader 컴포넌트 렌더링
- 헤더 검색 메뉴 제거, 로고 위치 정중앙으로 수정
- loader portal position absolute -> fixed로 변경
- 리뷰 에디터 첨부 파일 삭제 버튼 스타일 수정
#107
=> feat: 회원 리뷰 조회, 작성, 수정 구현

src/hooks/useEditProfile.ts, src/hooks/useForm.ts, src/hooks/useJoin.ts, src/hooks/useLeave.ts, src/hooks/useLogin.ts, src/hooks/useWriteReview.ts, src/routes/Join.tsx, src/routes/Login.tsx, src/routes/MyPage/EditProfile/index.tsx, src/routes/MyPage/Leave/index.tsx, src/routes/router/publicRoutes.tsx
api 요청 시 로딩 추가
적용 대상
- 회원가입, 로그인, 회원 정보 조회/수정, 회원 탈퇴, 리뷰 작성/수정 시 필요한 데이터 조회
비회원 주문 조회 라우터 삭제
#141
=> feat: api 요청 시 로딩 추가

src/hooks/useForm.ts, src/routes/Login.tsx, src/routes/router/privateRoutes.tsx
구글 로그인 구현 및 vercel 배포 후 새로고침 시 404 오류 수정
vercel.json 생성
#150
=> feat: 구글 로그인 구현 및 vercel 배포 404 오류 수정

src/routes/Product/Review/index.tsx
- 포토 리뷰 개수가 7개 이상일 경우만 전체보기 버튼 렌더링
#148
=> feat: 상품 상세페이지 리뷰가 없을 경우 메시지 추가

src/api/ProductApi.ts, src/components/ProductCard/index.tsx, src/components/ReviewCard/Content.tsx, src/hooks/useProductDetail.ts, src/hooks/useProductInfo.ts, src/routes/Order/ProductInfo.tsx, src/routes/Product/Detail.tsx, src/routes/Product/OptionProduct.tsx, src/routes/Product/index.tsx, src/types/global.d.ts
상품 상세페이지 관련 기능 추가
- 상품 상세 조회 요청 api 구현
- 장바구니 담기, 주문하기 관련 함수 구현
- 관심상품 추가/삭제를 위한 LikeButton 컴포넌트 추가 및 스타일 변경
- 페이지 url 경로 변경
#137
=> feat: 상품 상세페이지 관련 기능 추가

src/api/ProductApi.ts, src/hooks/useProductDetail.ts, src/hooks/useProductInfo.ts, src/routes/Product/Detail.tsx, src/routes/Product/index.tsx
상품 상세 관련 기능 변경 및 조회 요청시 로딩 상태 추가
- 상품 상세 조회 요청 url 변경
- 상품 조회시 로딩상태일때는 Loader 컴포넌트를 보여주기
- 옵션이 없는 카테고리 상품일경우(소품, 잡화 등) 옵션 UI 제거, 기능 추가
#137
=> 상품 상세 관련 기능 변경 및 조회 요청시 로딩 상태 추가

src/api/AuthApi.ts, src/hooks/useLogout.ts
로그아웃 로직 수정
- 로그아웃 api 추가
- useLogout에 로그아웃 요청 추가
#87
=> refactor: 로그아웃 로직 수정

src/components/Carousel/style.ts, src/components/ProductCarousel/style.ts, src/components/VisualSection/style.ts, src/routes/Brand/Detail.tsx
- 캐러셀 화살표 아이콘 색상 변경 + 그림자 추가
https://github.com/imdaxsz/orday-front-end/assets/80813703/de19d867-420c-4364-bba6-393b18bb7f1b
- 브랜드 상품 목록 ProductCard NEW 태그 제거
#157
=> refactor: 디자인 변경 사항 적용

src/hooks/useBrandList.ts, src/hooks/useReivewList.ts, src/routes/Brand/List.tsx, src/routes/Like/Brand.tsx, src/routes/Review/List.tsx
브랜드 목록 조회, 회원 리뷰 목록 조회 로딩 추가
#167
=> refactor: 브랜드 목록 조회, 회원 리뷰 목록 조회 로딩 추가

src/api/OrderApi.ts, src/routes/MyPage/OrderList/OrderInfo.tsx, src/routes/MyPage/OrderList/OrderListBox.tsx, src/routes/Order/OrderConfirm.tsx, src/routes/Order/ProductInfo.tsx, src/types/global.d.ts
- 주문 내역 상태 표시 및 주문 완료 페이지 변경
- 각 주문 상태에 따른 OrderListBox 주문상태 name 표시
- 주문 완료 페이지 주문번호, 주문일자 변경
- OrderConfirm 타입 추가
#153 #113 #79
=> feat: 주문 내역 상태 표시 및 주문 완료 페이지 변경

src/api/ProductApi.ts
리뷰 대상 상품 조회 요청 url 수정 배포 환경에 반영
=> fix: 리뷰 대상 상품 조회 요청 url 수정

src/constants/index.ts, src/hooks/useOrderForm.ts, src/hooks/useProductAction.ts, src/routes/Order/DeliveryInfo.tsx, src/routes/Order/ProductInfo.tsx, src/routes/Order/index.tsx, src/routes/Product/Detail.tsx, src/utils/index.ts
- 상품 주문페이지 관련 변경
- 상품 주문 확인모달창 확인 클릭시 closeModal 적용
- util폴더에 장바구니 또는 상품 주문할때의 상품들의 금액을 계산하는 calculateItemvalues 함수 구현
- 주문폼 유효성 검사 및 제출 관련 useOrderForm 추가
- 초기 주문폼 데이터, 배송요청사항 데이터 constants 폴더로 이동
#184
=> refactor: 상품 주문페이지 관련 변경

src/components/ReviewCard/Content.tsx, src/components/ReviewCard/style.ts, src/hooks/useToggleLike.ts
리뷰 좋아요 개수 버그 수정 및 최신 리뷰 이미지 렌더링 조건 추가
- 리뷰 이미지가 있을 경우에만 이미지 영역 렌더링
#191
=> fix: 리뷰 좋아요 개수 버그 수정 및 최신 리뷰 이미지 렌더링 조건 추가

src/components/CheckBox/index.tsx, src/components/Head/index.tsx, src/components/Header/index.tsx, src/components/LikeButton.tsx, src/routes/Cart/ProductItem.tsx, src/routes/MyPage/OrderList/OrderListBox.tsx, src/routes/Order/ProductInfo.tsx, src/routes/Product/index.tsx
웹 성능 최적화
- LightHouse의 웹접근성, 검색엔진 최적화 점수 개선
- 태그의 aria-label 이름 추가
- 이미지태그에 alt값 추가
- meta태그 description 설정
- 상품이미지 가로세로 비율 유지
#190
=> feat: 웹 성능 최적화

src/components/CheckBox/index.tsx, src/components/Dropdown/index.tsx, src/components/Head/index.tsx, src/components/Header/index.tsx, src/components/LikeButton.tsx, src/components/ReviewCard/Content.tsx, src/components/ReviewCard/style.ts, src/constants/index.ts, src/hooks/useForm.ts, src/hooks/useOrderForm.ts, src/hooks/useProductAction.ts, src/hooks/useToggleLike.ts, src/routes/Cart/ProductItem.tsx, src/routes/Cart/index.tsx, src/routes/Category.tsx, src/routes/MyPage/OrderList/OrderListBox.tsx, src/routes/Order/DeliveryInfo.tsx, src/routes/Order/OrderConfirm.tsx, src/routes/Order/ProductInfo.tsx, src/routes/Order/index.tsx, src/routes/Product/Detail.tsx, src/routes/Product/index.tsx, src/types/global.d.ts, src/utils/index.ts
=> deploy: 추가 구현 및 변경 사항 반영

src/components/AuthHeader.tsx, src/components/Carousel/index.tsx, src/components/ReviewCard/Action.tsx, src/components/ReviewCard/style.ts, src/components/SelectBox/index.tsx, src/components/VisualSection/index.tsx, src/hooks/useEditProfile.ts, src/hooks/useJoin.ts, src/hooks/useToggleLike.ts, src/routes/Brand/Detail.tsx, src/routes/Brand/List.tsx, src/routes/Join.tsx, src/routes/Login/index.tsx, src/routes/MyPage/EditProfile/index.tsx, src/routes/Order/DeliveryInfo.tsx, src/routes/Order/OrderConfirm.tsx, src/routes/Product/Review/SimpleReviewCard.tsx, src/routes/Review/ReviewItem.tsx
웹 성능 최적화 및 코드 리팩토링
- input을 비롯한 일부 요소 aria-label 추가 
- 이미지 alt 추가
- 이미지 object-fit 추가
- selectbox id 값 변경, option data-id 추가
- 브랜드 상품 목록 레이아웃 간격 조정 및 로딩 추가
#196
=> refactor: 웹 성능 최적화 및 코드 리팩토링

src/components/AuthHeader.tsx, src/components/Carousel/index.tsx, src/components/CheckBox/style.ts, src/components/ReviewCard/Action.tsx, src/components/ReviewCard/style.ts, src/components/SelectBox/index.tsx, src/components/VisualSection/index.tsx, src/hooks/useEditProfile.ts, src/hooks/useJoin.ts, src/hooks/useProductInfo.ts, src/hooks/useProductList.ts, src/hooks/useToggleLike.ts, src/routes/Brand/Detail.tsx, src/routes/Brand/List.tsx, src/routes/Cart/index.tsx, src/routes/Category.tsx, src/routes/Join.tsx, src/routes/Login/index.tsx, src/routes/MyPage/EditProfile/index.tsx, src/routes/Order/DeliveryInfo.tsx, src/routes/Order/OrderConfirm.tsx, src/routes/Product/OptionProduct.tsx, src/routes/Product/Review/SimpleReviewCard.tsx, src/routes/Review/ReviewItem.tsx
개선 사항 반영
웹 성능 최적화, 리팩토링, 버그 수정
=> deploy: 개선 사항 반영
